* commands reworked to be includeable (sh source)

diff --git a/host/tarball/share/myx.common/bin/lib/async b/host/tarball/share/myx.common/bin/lib/async
--- a/host/tarball/share/myx.common/bin/lib/async
+++ b/host/tarball/share/myx.common/bin/lib/async
@@ -2,7 +2,7 @@
 
 ##### !!! This script is universal for FreeBSD, Darwin, Ubuntu. !!! #####
 
-async(){
+Async(){
 	case "$1" in
 			"")
 				echo "async: prefix text argument is required!" >&2 ; exit 1
@@ -22,17 +22,20 @@ async(){
 	shift
 	
     echo "$PREFTEXT: starting async..."
-    echo "" | $@ 2>&1 | sed -e "s/^/$PREFTEXT: /" & # parallel
+    echo "" | $@ 2>&1 | sed -e "s/^/$PREFTEXT: /" & # parallel \
+    	&& echo "$PREFTEXT: successfully finished."\
+    	|| echo "$PREFTEXT: ERROR: exited with error status."
 }
 
-
-if [ "async" = "`basename $0`" ] ; then
-	if [ -z "$1" ] ; then
-		echo "Syntax: myx.common lib/async [-1|-2|-3|<prefix-text>] command [... arguments]" >&2
-		echo "    when -1, -2 or -3 is used in place of 'prefix text' argument" >$2
-		echo "    the corresponding following argument of the command is used." >$2
-		exit 1
-	fi
-	set -e
-	async $@
-fi
+case "$0" in
+	*/myx.common/bin/lib/async) 
+		if [ -z "$1" ] ; then
+			echo "Syntax: myx.common lib/async [-1|-2|-3|<prefix-text>] command [... arguments]" >&2
+			echo "    when -1, -2 or -3 is used in place of 'prefix text' argument" >$2
+			echo "    the corresponding following argument of the command is used." >$2
+			exit 1
+		fi
+		set -e
+		Async $@
+	;;
+esac
diff --git a/host/tarball/share/myx.common/bin/which b/host/tarball/share/myx.common/bin/which
--- a/host/tarball/share/myx.common/bin/which
+++ b/host/tarball/share/myx.common/bin/which
@@ -1,23 +1,23 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 # This script is universal for FreeBSD, Darwin, Ubuntu.
 
-Help(){
-	echo "'myx.common' script commands:"
-	
-	for ITEM in $(find "/usr/local/share/myx.common/bin" -type f | sed "s,/usr/local/share/myx.common/bin/,,g" | sort); do
-		echo "  $ITEM"
-	done
+Which(){
+	local COMMAND="$1"
+	[ -z "$COMMAND" ] && echo "Which: COMMAND argument is required!" && exit 1
+	local CHECK="/usr/local/share/myx.common/bin/$COMMAND"
+	[ -f "$CHECK" ] && echo "$CHECK" && return 0
+	return 1
 }
 
 case "$0" in
-	*/myx.common/bin/help) 
+	*/myx.common/bin/which) 
 		if [ -z "$1" ] ; then
 			echo "Syntax: myx.common which MYX-COMMON-COMMAND" >&2
 			echo "    outputs a full path to stdout or dies with error exit code." >&2
 			exit 1
 		fi
 		set -e
-		Help $@
+		Which $@
 	;;
 esac
