* install/ensure - reorganised

diff --git a/host/tarball/share/myx.common/bin/lib/installEnsurePackage b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
--- a/host/tarball/share/myx.common/bin/lib/installEnsurePackage
+++ b/host/tarball/share/myx.common/bin/lib/installEnsurePackage
@@ -3,33 +3,47 @@
 ##### !!! THIS SCRIPT SHOULD BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
 #####
-##### Note: must support following keywords: bash screen git rsync java 
+##### Note: must support following keywords: bash screen git rsync java go
 #####
 
-. "/usr/local/share/myx.common/bin/user/requireRoot"
+type UserRequireRoot >/dev/null 2>&1 || \
+	. "/usr/local/share/myx.common/bin/user/requireRoot"
+
+InstallEnsurePackageTransformPackageName(){
+		case "$1" in
+				*)
+					echo "$1"
+		        	return 0
+					;;
+		esac
+}
 
 InstallEnsurePackage(){
 	UserRequireRoot "InstallEnsurePackage"
 
-	local UTILITY_NAME="$1"
-	[ -z "$UTILITY_NAME" ] && echo "The utility name is required!" && exit 1
+	local NAME="$1"
+	[ -z "$NAME" ] && echo "The utility name is required!" && exit 1
 
-	local PACKAGE_NAME="${2:-$UTILITY_NAME}"
-	
-	if [ ! -z "`which $UTILITY_NAME`" ] ; then \
-		echo "Utility is present: $UTILITY_NAME, skip" >&2
-	 else \
+	local LIST=""
 
-		echo "myx.common lib/installEnsurePackage: abstract method" >&2
-		exit 1 
+	for NAME in $@ ; do
+		[ ! -z "`which $NAME`" ] \
+			&& echo "ensure: $NAME already present, skip" >&2 \
+			|| LIST="$LIST `InstallEnsurePackageTransformPackageName $NAME`"
+	done
 
-	fi
+	echo "myx.common lib/installEnsurePackage: abstract method" >&2
+	exit 1 
+
+	[ -z "$LIST" ] \
+		&& echo "all packages installed." >&2 \
+		|| myx.common lib/installEnsurePackage $LIST
 }
 
 case "$0" in
 	*/myx.common/bin/lib/installEnsurePackage) 
 		if [ -z "$1" ] ; then
-			echo "Syntax: myx.common lib/installEnsurePackage utility_name [package_name]" >&2
+			echo "Syntax: myx.common lib/installEnsurePackage utility_name [utility_name2 [...]]" >&2
 			exit 1
 		fi
 		set -e
