+ getBaseHomeDirectory --user argument

diff --git a/host/tarball/share/myx.common/bin/lib/installAuthorizedKey b/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
--- a/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
+++ b/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
@@ -18,12 +18,14 @@ InstallAuthorizedKey(){
 	local NAME="$1"
 	local KEY="$2"
 
-	test ! -z "$NAME" || ( echo "InstallAuthorizedKey: username is required!" >&2 ; exit 1 )
-	test ! -z "$KEY" || ( echo "InstallAuthorizedKey: key is required!" >&2 ; exit 2 )
+	set -e
+
+	test ! -z "$NAME" || ( echo "InstallAuthorizedKey: username is required!" >&2 ; return 1 )
+	test ! -z "$KEY" || ( echo "InstallAuthorizedKey: key is required!" >&2 ; return 2 )
 
 	test "$NAME" = "`whoami`" || UserRequireRoot "InstallAuthorizedKey(AsRoot)"
 
-	local HOME="`OsGetBaseHomeDirectory`/$NAME"
+	local HOME="`OsGetBaseHomeDirectory --user "$NAME"`"
 	local KEYS="$HOME/.ssh/authorized_keys"
 	
 	mkdir -p "$HOME/.ssh"
@@ -39,6 +41,11 @@ InstallAuthorizedKey(){
 
 case "$0" in
 	*/myx.common/bin/lib/installAuthorizedKey) 
+		if [ -z "$1" -o "$1" = "--help" ] ; then
+			echo "Syntax: myx.common lib/installAuthorizedKey <user-name> <ssh-key>" >&2
+			exit 1
+		fi
+		set -e
 		InstallAuthorizedKey "$@"
 	;;
 esac
diff --git a/host/tarball/share/myx.common/bin/os/getBaseHomeDirectory b/host/tarball/share/myx.common/bin/os/getBaseHomeDirectory
--- a/host/tarball/share/myx.common/bin/os/getBaseHomeDirectory
+++ b/host/tarball/share/myx.common/bin/os/getBaseHomeDirectory
@@ -3,16 +3,37 @@
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
 OsGetBaseHomeDirectory(){
-	# `echo /home`
 	echo "ERROR: OsGetBaseHomeDirectory must be re-implemented" >&2
 	exit 1
+
+	[ -z "$1" ] && \
+		echo "/home" && \
+		return 0
+		
+	set -e
+	if [ "$1" = "--user" ] ; then
+		[ -z "$2" ] && \
+			echo "OsGetBaseHomeDirectory: username required after --user " >&2 && \
+			return 1
+			
+		local HOME_PATH="`grep "^$2\\:" /etc/passwd | cut -d":" -f6`"
+		 
+		[ -z "$HOME_PATH" ] && \
+			echo "OsGetBaseHomeDirectory: no such user: $2" >&2 && \
+			return 1
+			
+		echo "$HOME_PATH"
+		return 0
+	fi
+	
+	echo "OsGetBaseHomeDirectory: Invalid arguments: $@" >&2
 }
 
 
 case "$0" in
 	*/myx.common/bin/os/getBaseHomeDirectory) 
 		if [ "$1" = "--help" ] ; then
-			echo "Syntax: myx.common os/getBaseHomeDirectory" >&2
+			echo "Syntax: myx.common os/getBaseHomeDirectory [--user username]" >&2
 			exit 1
 		fi
 		set -e
