* minor: ' [ ! -z ' -> ' [ -n '

diff --git a/host/tarball/share/myx.common/bin/lib/installAuthorizedKey b/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
--- a/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
+++ b/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
@@ -20,14 +20,14 @@ InstallAuthorizedKey(){
 
 	set -e
 
-	test ! -z "$NAME" || ( echo "⛔ ERROR: InstallAuthorizedKey: username is required!" >&2 ; return 1 )
-	test ! -z "$KEY" || ( echo "⛔ ERROR: InstallAuthorizedKey: key is required!" >&2 ; return 2 )
+	test -n "$NAME" || ( echo "⛔ ERROR: InstallAuthorizedKey: username is required!" >&2 ; return 1 )
+	test -n "$KEY" || ( echo "⛔ ERROR: InstallAuthorizedKey: key is required!" >&2 ; return 2 )
 
 	test "$NAME" = "`whoami`" || UserRequireRoot "InstallAuthorizedKey(AsRoot)"
 
 	local HOME="`OsGetUserHome --user "$NAME"`"
 
-	test ! -z "$HOME" || ( echo "InstallAuthorizedKey: no home for $NAME!" >&2 ; return 3 )
+	test -n "$HOME" || ( echo "InstallAuthorizedKey: no home for $NAME!" >&2 ; return 3 )
 	test -d "$HOME" || ( echo "InstallAuthorizedKey: home directory $HOME is missing for $NAME!" >&2 ; return 4 )
 
 	local KEYS="$HOME/.ssh/authorized_keys"
diff --git a/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey b/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey
--- a/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey
+++ b/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey
@@ -25,11 +25,11 @@ InstallRootAuthorizedKey(){
 
 	local KEY="$1"
 
-	test ! -z "$KEY" || ( echo "InstallRootAuthorizedKey: key is required!" ; exit 2 )
+	test -n "$KEY" || ( echo "InstallRootAuthorizedKey: key is required!" ; exit 2 )
 
 	local HOME="`OsGetUserHome --user root`"
 
-	test ! -z "$HOME" || ( echo "InstallAuthorizedKey: no home for $NAME!" >&2 ; return 3 )
+	test -n "$HOME" || ( echo "InstallAuthorizedKey: no home for $NAME!" >&2 ; return 3 )
 	test -d "$HOME" || ( echo "InstallAuthorizedKey: home directory $HOME is missing for $NAME!" >&2 ; return 4 )
 
 	local KEYS="$HOME/.ssh/authorized_keys"
diff --git a/host/tarball/share/myx.common/bin/lib/replaceLine b/host/tarball/share/myx.common/bin/lib/replaceLine
--- a/host/tarball/share/myx.common/bin/lib/replaceLine
+++ b/host/tarball/share/myx.common/bin/lib/replaceLine
@@ -8,8 +8,8 @@ ReplaceLine(){
 		local DO_CREATE=true ; shift
 	fi
 	local fileName="$1" textSearch="$2" lineReplace="$3"
-	[ ! -z "$fileName" ] || { echo "⛔ ERROR: ReplaceLine: fileName argument is required!" >&2 ; return 1 ; }
-	if [ ! -f "$fileName" ] && [ ! -z "$DO_CREATE" ] ; then
+	[ -n "$fileName" ] || { echo "⛔ ERROR: ReplaceLine: fileName argument is required!" >&2 ; return 1 ; }
+	if [ ! -f "$fileName" ] && [ -n "$DO_CREATE" ] ; then
 		mkdir -p "$(dirname "$fileName")" || { echo "⛔ ERROR: ReplaceLine: can't create directory: $(dirname "$fileName")" >&2 ; return 1 ; }
 		touch "$fileName" || { echo "⛔ ERROR: ReplaceLine: can't create file $fileName" >&2 ; return 1 ; }
 	fi
