+ install[Root]AuthorizedKey check for home directory

diff --git a/host/tarball/share/myx.common/bin/lib/installAuthorizedKey b/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
--- a/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
+++ b/host/tarball/share/myx.common/bin/lib/installAuthorizedKey
@@ -26,6 +26,10 @@ InstallAuthorizedKey(){
 	test "$NAME" = "`whoami`" || UserRequireRoot "InstallAuthorizedKey(AsRoot)"
 
 	local HOME="`OsGetUserHome --user "$NAME"`"
+
+	test ! -z "$HOME" || ( echo "InstallAuthorizedKey: no home for $NAME!" >&2 ; return 3 )
+	test -d "$HOME" || ( echo "InstallAuthorizedKey: home directory $HOME is missing for $NAME!" >&2 ; return 4 )
+
 	local KEYS="$HOME/.ssh/authorized_keys"
 	
 	mkdir -p "$HOME/.ssh"
diff --git a/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey b/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey
--- a/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey
+++ b/host/tarball/share/myx.common/bin/lib/installRootAuthorizedKey
@@ -28,6 +28,10 @@ InstallRootAuthorizedKey(){
 	test ! -z "$KEY" || ( echo "InstallRootAuthorizedKey: key is required!" ; exit 2 )
 
 	local HOME="`OsGetUserHome --user root`"
+
+	test ! -z "$HOME" || ( echo "InstallAuthorizedKey: no home for $NAME!" >&2 ; return 3 )
+	test -d "$HOME" || ( echo "InstallAuthorizedKey: home directory $HOME is missing for $NAME!" >&2 ; return 4 )
+
 	local KEYS="$HOME/.ssh/authorized_keys"
 	
 	mkdir -p "$HOME/.ssh"
