* lib/{async|prefix|replaceLine} help moved out

diff --git a/host/tarball/share/myx.common/bin/lib/prefix b/host/tarball/share/myx.common/bin/lib/prefix
--- a/host/tarball/share/myx.common/bin/lib/prefix
+++ b/host/tarball/share/myx.common/bin/lib/prefix
@@ -10,35 +10,45 @@
 
 
 Prefix(){
-	local verbose=""
-	if [ "--verbose" = "$1" ] ; then
-		shift
-		local verbose="true"
-	fi
+	local verbose="" prefixLimit=64 prefixElapsed=""
+	while true; do
+		case "$1" in
+			--verbose|-v) verbose="$1" ; shift ;;
+			--elapsed|-e) prefixElapsed="$1" ; shift ;;
+			--prefix-limit)
+				: "${2:?"⛔ ERROR: $1 <number> - numeric argument is expected!"}"
+				case "$2" in
+					''|*[!0-9]*) echo "⛔ ERROR: $1 expects a numeric value, but got '$2'" >&2 ; exit 1 ;;
+				esac				
+				prefixLimit="$2"; shift ; shift
+			;;
+			*) break ;;
+		esac
+	done
 
 	case "$1" in
 			"")
 				echo "⛔ ERROR: prefix: prefix text argument is required!" >&2 ; exit 1
 				;;
 	        -1)
-				local PREFTEXT="`basename $2`"
+				local PREFTEXT="`basename $2`" ; shift
 	            ;;
 	        -2)
-				local PREFTEXT="`basename $3`"
+				local PREFTEXT="`basename $3`" ; shift
 	            ;;
 	        -3)
-				local PREFTEXT="`basename $4`"
+				local PREFTEXT="`basename $4`" ; shift
 	            ;;
 	        --)
-				local PREFTEXT="${!#}"
+				local PREFTEXT="${!#}" ; shift
 	            ;;
 	        *)
-				local PREFTEXT="$1"
+				local PREFTEXT="$1" ; shift
 				;;
 	esac
-	shift
+	
 
-	local PREFTEXT="`printf %s "$PREFTEXT" | tr '^' '-' | tr -d '\n' `"
+	local PREFTEXT="`printf %s "${PREFTEXT:0:$prefixLimit}" | tr '^' '-' | tr -d '\n' `"
 	
 	#!/usr/bin/env bash
 	# local PREFTEXT="` tr '^' '-' <<<"$PREFTEXT" | tr -d '\n' `"
@@ -47,23 +57,21 @@ Prefix(){
 
     [ -z "$verbose" ] || echo "$PREFTEXT: starting..."
     (	"$@" 2>&1 \
-	    	&& ( [ -z "$verbose" ] || echo "." ) \
-    		|| ( EXITCODE=$? ; set +x ; echo "⛔ ERROR: exited with error status ($EXITCODE)" ; exit $EXITCODE ) \
-   	) | $SedLineReader -e "s^\^^$PREFTEXT: ^" 1>&2
+	    	&& { [ -z "$verbose" ] || echo "." ; } \
+    		|| { EXITCODE=$? ; set +x ; echo "⛔ ERROR: exited with error status ($EXITCODE)" ; exit $EXITCODE ; } \
+   	) | $SedLineReader -e 's^\^^'"$PREFTEXT"': ^' 1>&2
    	
 #	(	( echo "" | Unbuffer "$@" 2>&1 ) \
 #	    	&& echo "finished." \
 #    		|| echo "⛔ ERROR: exited with error status." \
-#	) | $SedLineReader -e "s^\^^$PREFTEXT: ^"
+#	) | $SedLineReader -e 's^\^^'"$PREFTEXT"': ^'
 
 }
 
 case "$0" in
 	*/myx.common/bin/lib/prefix) 
-		if [ -z "$1" ] ; then
-			echo "Syntax: myx.common lib/prefix [--verbose] [-1|-2|-3|<prefix-text>] command [... arguments]" >&2
-			echo "    when -1, -2 or -3 is used in place of 'prefix text' argument" >$2
-			echo "    the corresponding following argument of the command is used." >$2
+		if [ -z "$1" ] || [ "$1" == '--help' ] ; then
+			. "${MYXROOT:-/usr/local/share/myx.common}/include/help/lib/prefix.help.include" >&2
 			exit 1
 		fi
 		set -e
