* icons in errors

diff --git a/host/tarball/share/myx.common/bin/lib/prefix b/host/tarball/share/myx.common/bin/lib/prefix
--- a/host/tarball/share/myx.common/bin/lib/prefix
+++ b/host/tarball/share/myx.common/bin/lib/prefix
@@ -18,7 +18,7 @@ Prefix(){
 
 	case "$1" in
 			"")
-				echo "ERROR: prefix: prefix text argument is required!" >&2 ; exit 1
+				echo "⛔ ERROR: prefix: prefix text argument is required!" >&2 ; exit 1
 				;;
 	        -1)
 				local PREFTEXT="`basename $2`"
@@ -48,12 +48,12 @@ Prefix(){
     [ -z "$verbose" ] || echo "$PREFTEXT: starting..."
     (	"$@" 2>&1 \
 	    	&& ( [ -z "$verbose" ] || echo "." ) \
-    		|| ( EXITCODE=$? ; set +x ; echo "ERROR: exited with error status ($EXITCODE)" ; exit $EXITCODE ) \
+    		|| ( EXITCODE=$? ; set +x ; echo "⛔ ERROR: exited with error status ($EXITCODE)" ; exit $EXITCODE ) \
    	) | $SedLineReader -e "s^\^^$PREFTEXT: ^" 1>&2
    	
 #	(	( echo "" | Unbuffer "$@" 2>&1 ) \
 #	    	&& echo "finished." \
-#    		|| echo "ERROR: exited with error status." \
+#    		|| echo "⛔ ERROR: exited with error status." \
 #	) | $SedLineReader -e "s^\^^$PREFTEXT: ^"
 
 }
diff --git a/host/tarball/share/myx.common/bin/lib/replaceLine b/host/tarball/share/myx.common/bin/lib/replaceLine
--- a/host/tarball/share/myx.common/bin/lib/replaceLine
+++ b/host/tarball/share/myx.common/bin/lib/replaceLine
@@ -8,15 +8,15 @@ ReplaceLine(){
 		local DO_CREATE=true ; shift
 	fi
 	local fileName="$1" textSearch="$2" lineReplace="$3"
-	[ ! -z "$fileName" ] || { echo "ERROR: ReplaceLine: fileName argument is required!" >&2 ; return 1 ; }
+	[ ! -z "$fileName" ] || { echo "⛔ ERROR: ReplaceLine: fileName argument is required!" >&2 ; return 1 ; }
 	if [ ! -f "$fileName" ] && [ ! -z "$DO_CREATE" ] ; then
-		mkdir -p "$(dirname "$fileName")" || { echo "ERROR: ReplaceLine: can't create directory: $(dirname "$fileName")" >&2 ; return 1 ; }
-		touch "$fileName" || { echo "ERROR: ReplaceLine: can't create file $fileName" >&2 ; return 1 ; }
+		mkdir -p "$(dirname "$fileName")" || { echo "⛔ ERROR: ReplaceLine: can't create directory: $(dirname "$fileName")" >&2 ; return 1 ; }
+		touch "$fileName" || { echo "⛔ ERROR: ReplaceLine: can't create file $fileName" >&2 ; return 1 ; }
 	fi
-	[ -f "$fileName" ] || { echo "ERROR: ReplaceLine: $fileName file is expected!" >&2 ; return 1 ; }
-	[ -r "$fileName" ] || { echo "ERROR: ReplaceLine: $fileName file is not readable!" >&2 ; return 1 ; }
-	[ -w "$fileName" ] || { echo "ERROR: ReplaceLine: $fileName file is not writable!" >&2 ; return 1 ; }
-	[ -w "$(dirname "$fileName")" ] || { echo "ERROR: ReplaceLine: $fileName parent directory is not writable!" >&2 ; return 1 ; }
+	[ -f "$fileName" ] || { echo "⛔ ERROR: ReplaceLine: $fileName file is expected!" >&2 ; return 1 ; }
+	[ -r "$fileName" ] || { echo "⛔ ERROR: ReplaceLine: $fileName file is not readable!" >&2 ; return 1 ; }
+	[ -w "$fileName" ] || { echo "⛔ ERROR: ReplaceLine: $fileName file is not writable!" >&2 ; return 1 ; }
+	[ -w "$(dirname "$fileName")" ] || { echo "⛔ ERROR: ReplaceLine: $fileName parent directory is not writable!" >&2 ; return 1 ; }
 
 	set -e
 		
diff --git a/host/tarball/share/myx.common/bin/lib/setupShellCompletion b/host/tarball/share/myx.common/bin/lib/setupShellCompletion
--- a/host/tarball/share/myx.common/bin/lib/setupShellCompletion
+++ b/host/tarball/share/myx.common/bin/lib/setupShellCompletion
@@ -9,7 +9,7 @@ SetupShellCompletion(){
 	
 	local utilityName="$1"
 	if [ -z "$utilityName" ] ; then
-		echo "ERROR: SetupShellCompletion: utilityName is required!" >&2
+		echo "⛔ ERROR: SetupShellCompletion: utilityName is required!" >&2
 		exit 1
 	fi
 
@@ -20,7 +20,7 @@ SetupShellCompletion(){
 	case "$2" in
 		--command)
 			if [ -z "$3" ] ; then
-				echo "ERROR: SetupShellCompletion: listCommand is required!" >&2
+				echo "⛔ ERROR: SetupShellCompletion: listCommand is required!" >&2
 				exit 1
 			fi
 			local listCommand="$3"
@@ -28,7 +28,7 @@ SetupShellCompletion(){
 			
 		--directory)
 			if [ -z "$3" ] ; then
-				echo "ERROR: SetupShellCompletion: listDirectory is required!" >&2
+				echo "⛔ ERROR: SetupShellCompletion: listDirectory is required!" >&2
 				exit 1
 			fi
 			local listCommand="find \"$3\" -type f | sed \"s,$3/,,g\" | sort"
@@ -51,7 +51,7 @@ SetupShellCompletion(){
 			;;
 	
 		*)
-			echo "ERROR: SetupShellCompletion: invalid mode: $2" >&2
+			echo "⛔ ERROR: SetupShellCompletion: invalid mode: $2" >&2
 			exit 1
 	esac 
 	
diff --git a/host/tarball/share/myx.common/bin/os/getCommonScreenRc b/host/tarball/share/myx.common/bin/os/getCommonScreenRc
--- a/host/tarball/share/myx.common/bin/os/getCommonScreenRc
+++ b/host/tarball/share/myx.common/bin/os/getCommonScreenRc
@@ -4,7 +4,7 @@
 
 OsGetCommonScreenRc(){
 	# `echo /usr/local/etc/screenrc`
-	echo "ERROR: OsGetCommonScreenRc must be re-implemented" >&2
+	echo "⛔ ERROR: OsGetCommonScreenRc must be re-implemented" >&2
 	exit 1
 }
 
diff --git a/host/tarball/share/myx.common/bin/os/getCpuCount b/host/tarball/share/myx.common/bin/os/getCpuCount
--- a/host/tarball/share/myx.common/bin/os/getCpuCount
+++ b/host/tarball/share/myx.common/bin/os/getCpuCount
@@ -3,7 +3,7 @@
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
 OsGetCpuCount(){
-	echo "ERROR: OsGetCpuCount must be re-implemented" >&2
+	echo "⛔ ERROR: OsGetCpuCount must be re-implemented" >&2
 	exit 1
 }
 
diff --git a/host/tarball/share/myx.common/bin/os/getRamBytes b/host/tarball/share/myx.common/bin/os/getRamBytes
--- a/host/tarball/share/myx.common/bin/os/getRamBytes
+++ b/host/tarball/share/myx.common/bin/os/getRamBytes
@@ -3,7 +3,7 @@
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
 OsGetRamBytes(){
-	echo "ERROR: OsGetRamBytes must be re-implemented" >&2
+	echo "⛔ ERROR: OsGetRamBytes must be re-implemented" >&2
 	exit 1
 }
 
diff --git a/host/tarball/share/myx.common/bin/os/getUserHome b/host/tarball/share/myx.common/bin/os/getUserHome
--- a/host/tarball/share/myx.common/bin/os/getUserHome
+++ b/host/tarball/share/myx.common/bin/os/getUserHome
@@ -3,7 +3,7 @@
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
 OsGetUserHome(){
-	echo "ERROR: OsGetUserHome must be re-implemented" >&2
+	echo "⛔ ERROR: OsGetUserHome must be re-implemented" >&2
 	exit 1
 
 	[ -z "$1" ] && \
@@ -13,13 +13,13 @@ OsGetUserHome(){
 	set -e
 	if [ "$1" = "--user" ] ; then
 		[ -z "$2" ] && \
-			echo "ERROR: OsGetUserHome: username required after --user " >&2 && \
+			echo "⛔ ERROR: OsGetUserHome: username required after --user " >&2 && \
 			return 1
 			
 		local HOME_PATH="`grep "^$2\\:" /etc/passwd | cut -d":" -f6`"
 		 
 		[ -z "$HOME_PATH" ] && \
-			echo "ERROR: OsGetUserHome: no such user: $2" >&2 && \
+			echo "⛔ ERROR: OsGetUserHome: no such user: $2" >&2 && \
 			return 1
 			
 		echo "$HOME_PATH"
diff --git a/host/tarball/share/myx.common/bin/os/getUtilityPackage b/host/tarball/share/myx.common/bin/os/getUtilityPackage
--- a/host/tarball/share/myx.common/bin/os/getUtilityPackage
+++ b/host/tarball/share/myx.common/bin/os/getUtilityPackage
@@ -29,7 +29,7 @@ OsGetUtilityPackage(){
 	
 	local REQ_UTIL_NAME="$1"
 	if [ -z "$REQ_UTIL_NAME" ] ; then
-		echo "ERROR: OsGetUtilityPackage: utilityName is required!" >&2
+		echo "⛔ ERROR: OsGetUtilityPackage: utilityName is required!" >&2
 		return 1
 	fi
 
diff --git a/host/tarball/share/myx.common/bin/os/getWheelGroupNames b/host/tarball/share/myx.common/bin/os/getWheelGroupNames
--- a/host/tarball/share/myx.common/bin/os/getWheelGroupNames
+++ b/host/tarball/share/myx.common/bin/os/getWheelGroupNames
@@ -4,7 +4,7 @@
 
 OsGetWheelGroupNames(){
 	# `echo wheel`
-	echo "ERROR: OsGetWheelGroupNames must be re-implemented" >&2
+	echo "⛔ ERROR: OsGetWheelGroupNames must be re-implemented" >&2
 	exit 1
 }
 
