* remoteContext

diff --git a/host/tarball/share/myx.common/bin/lib/remoteContext b/host/tarball/share/myx.common/bin/lib/remoteContext
--- a/host/tarball/share/myx.common/bin/lib/remoteContext
+++ b/host/tarball/share/myx.common/bin/lib/remoteContext
@@ -197,12 +197,36 @@ RemoteContext(){
 			[ "$1" = --do-ssh ] || sshOptions="$sshOptions -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
 			[ -z "$interactive" ] || sshOptions="$sshOptions -tt"
 			shift
+			local fifo=$(mktemp -u)
+			mkfifo "$fifo"
+			ssh $sshOptions "$@" '
+				command -v bash >/dev/null && exec bash -s
+				command -v sh >/dev/null && exec sh -s
+			' <"$fifo" &
+			exec 1> "$fifo"
+			rm "$fifo"
+			break
+			
+			ssh $sshOptions "$@" '
+				if [ -r /dev/fd/3 ]; then . /dev/fd/3; else eval "$(cat <&3)"; fi
+			' 3<"$fifo" </dev/tty &
+			exec 1> "$fifo"
+			rm "$fifo"
+			local USE_FIFO_CHANNELS=true
+			break
+		;;
 
+		--do-ssh|--do-ssh-once)
+			local sshOptions=
+			[ "$1" = --do-ssh ] || sshOptions="$sshOptions -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
+			[ -z "$interactive" ] || sshOptions="$sshOptions -tt"
+			shift
 			local fifo=$(mktemp -u)
 			mkfifo "$fifo"
 			ssh $sshOptions "$@" < "$fifo" &
-			exec > "$fifo"
+			exec 1> "$fifo"
 			rm "$fifo"
+			local USE_FIFO_CHANNELS=true
 			break
 		;;
 
@@ -236,10 +260,10 @@ RemoteContext(){
 	local templateRoot="${MYXROOT:-/usr/local/share/myx.common}/include/remote/"
 
 	if [ -n "$interactive" -o -n "$requireBash" ]; then
-		sleep .75
 		if [ -n "$interactive" ]; then
-			echo '[ -t 0 ] && stty -echo -echoctl erase "^H"'
-			echo
+			[ ! -t 0 ] || stty -echo; exec 0</dev/null
+			printf "[ -t 0 ] && stty -echo\n" '\b'
+			printf "[ -t 0 ] && stty -echoctl -ixon -ixoff erase \$'%s';PS1=\n" '\b'
 			{
 				cat "$templateRoot/step0-interactive-check-start-shell.sh.include"
 			} | RemoteContext --intern-one-liner-cat-for-script
@@ -248,25 +272,24 @@ RemoteContext(){
 				cat "$templateRoot/step0-unattended-check-start-shell.sh.include"
 			} | RemoteContext --intern-one-liner-cat-for-script
 		fi
-		sleep .05
 		for item in 1 2 3 4 5 6 7 8 9 0; do
-			awk 'BEGIN { for(i=1;i<=1024;i++)printf" \010"; }' # purge shell's buffer
+			awk 'BEGIN { for(i=1;i<=256;i++)printf" \010"; }' # purge shell's buffer
 			sleep .075
 		done
 		echo
 	fi
 
 	if [ -n "$interactive" ] ; then
-		sleep .05
-		echo
+		sleep .15
 		echo 'stty -echo'
 		echo 'PS1="\rRemote: ⌛︎ Interactive wrapper set.\r"'
-		printf '{ %s ; }\n' "$(
+#		printf '{ %s ; }\n' "$(
 			{
+				echo "LINES=$( tput lines ) COLUMNS=$( tput cols )"
 				cat "$templateRoot/step1-interactive-prefix.sh.include"
 				cat "$templateRoot/step2-interactive-prefix.sh.include"
 			} | RemoteContext --intern-one-liner-cat-for-script
-		)"
+#		)"
 		sleep .02
 		awk 'BEGIN { for(j=1;j<=32;j++){ for(i=1;i<=128;i++) printf"#"; printf"\n" } }' # purge shell's buffer
 		sleep .05
@@ -348,19 +371,19 @@ RemoteContext(){
 				-C "$basePath/" $relPaths \
 			| (
 				{ command -v openssl	>/dev/null 2>&1 && {
-					[ -z "$MDSC_DETAIL" ] || echo "Local: 📦 base64: using \"openssl\" to encode base64" >&2
+					[ -z "$MDSC_DETAIL" ] || echo "Local: 📦 base64: using 'openssl' to encode base64" >&2
 					openssl base64 -e -A 2>/dev/null || openssl enc -base64 -A
 				} } || \
 				{ command -v base64	>/dev/null 2>&1 && {
-					[ -z "$MDSC_DETAIL" ] || echo "Local: 📦 base64: using \"base64\" utility to encode" >&2
+					[ -z "$MDSC_DETAIL" ] || echo "Local: 📦 base64: using 'base64' utility to encode" >&2
 					base64 -w0
 				} } || \
 				{ command -v uuencode	>/dev/null 2>&1 && {
-					[ -z "$MDSC_DETAIL" ] || echo "Local: 📦 base64: using \"uuencode\" utility to encode" >&2
+					[ -z "$MDSC_DETAIL" ] || echo "Local: 📦 base64: using 'uuencode' utility to encode" >&2
 					uuencode -m packed.tbz | sed "1d; /^====\$/d"
 				} } || \
 				{
-					echo "$MDSC_CMD: ⛔ ERROR: can not detect base64 encoder, make sure: \"openssl\", \"base64\" or \"uuencode\" utility is available" >&2
+					echo "$MDSC_CMD: ⛔ ERROR: can not detect base64 encoder, make sure: 'openssl', 'base64' or 'uuencode' utility is available" >&2
 					set +e ; return 1
 				}
 			)
@@ -372,6 +395,14 @@ RemoteContext(){
 		# remote script will continue after this
 
 	done
+
+	if [ -n "$interactive" ] ; then
+		{ 
+			echo "export TERM=${TERM:-xterm-256color}"
+			echo 'tput reset >/dev/null 2>&1'
+			cat "$templateRoot/step4-interactive-session.sh.include" 
+		} | RemoteContext --intern-no-comment-cat-for-script
+	fi
 
 	printf '%b' "$includeScripts" | awk '!seen[$0]++' | while IFS= read -r entry; do
 		[ -z "$verbose" ] || printf '%s\n' "Local: 📦 pack: embedding '${entry#$MMDAPP/}'" >&2
@@ -410,20 +441,21 @@ RemoteContext(){
 		echo "export TERM=${TERM:-xterm-256color}"
 
 		{ 
-			cat "$templateRoot/step4-interactive-suffix.sh.include" 
+			cat "$templateRoot/step5-interactive-suffix.sh.include" 
 		} | RemoteContext --intern-no-comment-cat-for-script
 
 		printf '\n#END-NON-INTERACTIVE#\n'
 
 		#awk 'BEGIN { for(i=1;i<=8192;i++)printf"#\010"; }' # purge shell's buffer
 		echo 'echo "Remote: ↪ interactive shell activate..." >&2'
-		
 		echo 'exec bash --noprofile --rcfile "$IMAGE_UNPACK_DIR/console.rc" -i'
 		#echo 'exec bash --noprofile --rcfile "$IMAGE_UNPACK_DIR/console.rc" -i < /dev/tty > /dev/tty 2>&1'
 		#echo 'exec script -q /dev/null bash --noprofile --rcfile "$IMAGE_UNPACK_DIR/console.rc" -i'
 
 		if [ -z "$force" ] || [[ ! -t 1 ]]; then
 			set -e
+			exec 0</dev/tty
+			stty sane
 			if true; then
 				trap "stty \"$(stty -g)\"" EXIT; stty raw; cat ; exit 0
 			elif command -v stdbuf >/dev/null; then
