* minor: Unbuffer: which -s -> command -v

diff --git a/host/tarball/share/myx.common/bin/lib/unbuffer b/host/tarball/share/myx.common/bin/lib/unbuffer
--- a/host/tarball/share/myx.common/bin/lib/unbuffer
+++ b/host/tarball/share/myx.common/bin/lib/unbuffer
@@ -6,19 +6,21 @@
 ## NOTE: because of linux gnu 'script' is not like others
 
 Unbuffer(){
-	if which -s script && which -s "$1" ; then
-		set -e
+	command -v "$1" >/dev/null || { echo "⛔ Unbuffer: command not found: $1" >&2; exit 1; }
+
+	# macosx?
+	export NSUnbufferedIO=YES
+	set -e
+
+	if command -v script >/dev/null; then
 		script -q /dev/null "$@"
 		return 0
 	fi
-	if which -s stdbuf && which -s "$1" ; then
-		set -e
+	if command -v stdbuf >/dev/null; then
 		stdbuf -i0 -o0 -e0 "$@"
 		return 0
 	fi
 
-	# macosx?
-	export NSUnbufferedIO=YES	
 	"$@"
 }
 
