! install/git & install/nativePackage

diff --git a/host/tarball/share/myx.common/bin/install/ensure/nativePackage b/host/tarball/share/myx.common/bin/install/ensure/nativePackage
--- a/host/tarball/share/myx.common/bin/install/ensure/nativePackage
+++ b/host/tarball/share/myx.common/bin/install/ensure/nativePackage
@@ -15,7 +15,10 @@ InstallEnsureNativePackage(){
 
 	UserRequireRoot "InstallEnsureNativePackage"
 
-	[ -z "$1" ] && echo "⛔ ERROR: InstallEnsureNativePackage: Arguments are expected!" && return 1
+	if [ -z "$1" ]; then 
+		echo "⛔ ERROR: InstallEnsureNativePackage: Arguments are expected!" >&2
+		return 1
+	fi
 
 	echo "myx.common install/ensure/nativePackage: abstract method" >&2
 	return 1 
