* git/clone{Pull|Sync} source code refactoring

diff --git a/host/tarball/share/myx.common/bin/git/clonePull b/host/tarball/share/myx.common/bin/git/clonePull
--- a/host/tarball/share/myx.common/bin/git/clonePull
+++ b/host/tarball/share/myx.common/bin/git/clonePull
@@ -3,39 +3,43 @@
 ##### !!! This script is universal for FreeBSD, Darwin, Ubuntu. !!! #####
 
 GitClonePull(){
-	local TGT_DIR="$1"
-	[ -z "$TGT_DIR" ] && echo "GitClonePull: TGT_DIR is required!" >&2 && exit 1
+	set -e
 
-	local SRC_URL="$2"
-	[ -z "$SRC_URL" ] && echo "GitClonePull: SRC_URL is required!" >&2 && exit 1
+	local tgtPath="$1"
+	[ -z "$tgtPath" ] && echo "GitClonePull: tgtPath is required!" >&2 && return 1
 
-	local BRANCH="$3"
+	local repoUrl="$2"
+	[ -z "$repoUrl" ] && echo "GitClonePull: repoUrl is required!" >&2 && return 1
+
+	local specificBranch="$3"
 	
-	local PWD="`pwd`"
+	local currentPath="`pwd`"
 	
-	[ -d "$TGT_DIR" ] && ({
-		cd "$TGT_DIR"
+	if [ -d "$tgtPath" ] ; then
+		cd "$tgtPath"
 		git rev-parse --abbrev-ref HEAD > /dev/null \
-				&& [ "`git rev-parse --abbrev-ref HEAD`" != "${BRANCH:-master}" ] \
-				&& cd "$TGT_DIR/.." \
-				&& rm -rf "$TGT_DIR" \
-			|| true
-	}) || true;
-	[ -d "$TGT_DIR" ] || ({
-	    echo "$TGT_DIR: creating..."
-	    mkdir -p "$TGT_DIR"
-	    git clone "$SRC_URL" "$TGT_DIR"
-	});
-	[ -d "$TGT_DIR" ] && ({
-	    cd "$TGT_DIR"
-	    echo "$TGT_DIR: updating..."
-	    git remote set-url origin "$SRC_URL"
-	    [ -n $BRANCH ] && git checkout $BRANCH
+			&& [ "`git rev-parse --abbrev-ref HEAD`" != "${specificBranch:-master}" ] \
+			&& cd "$tgtPath/.." \
+			&& rm -rf "$tgtPath" \
+		|| true
+	fi
+	if [ ! -d "$tgtPath" ] ; then
+	    echo "GitClonePull: $tgtPath: creating..." >&2
+	    mkdir -p "$tgtPath"
+	    git clone "$repoUrl" "$tgtPath"
+	fi
+	if [ -d "$tgtPath" ] ; then
+	    cd "$tgtPath"
+	    echo "GitClonePull: $tgtPath: updating..." >&2
+	    git remote set-url origin "$repoUrl"
+	    if [ -n $specificBranch ] ; then
+	    	git checkout $specificBranch
+	    fi
 	    git pull
-	    echo "$TGT_DIR: finished."
-	}) || true;
+	    echo "GitClonePull: $tgtPath: finished." >&2
+	fi
 	
-	cd "$PWD"
+	cd "$currentPath"
 }
 
 case "$0" in
diff --git a/host/tarball/share/myx.common/bin/git/cloneSync b/host/tarball/share/myx.common/bin/git/cloneSync
--- a/host/tarball/share/myx.common/bin/git/cloneSync
+++ b/host/tarball/share/myx.common/bin/git/cloneSync
@@ -3,77 +3,79 @@
 ##### !!! This script is universal for FreeBSD, Darwin, Ubuntu. !!! #####
 
 GitCloneSync(){
+	set -e
+
 	if [ "$1" = "--no-write" ] ; then
-		local NOWRITE=true
+		local noWrite=true
 		shift
 	fi
 	if [ "$1" = "--no-push" ] ; then
-		local NOWRITE=true
-		local NOPUSH=true
+		local noWrite=true
+		local noPush=true
 		shift
 	fi
 
-	local TGT_DIR="$1"
-	[ -z "$TGT_DIR" ] && echo "GitCloneSync: TGT_DIR is required!" >&2 && exit 1
+	local tgtPath="$1"
+	[ -z "$tgtPath" ] && echo "GitCloneSync: tgtPath is required!" >&2 && return 1
 
-	local SRC_URL="$2"
-	[ -z "$SRC_URL" ] && echo "GitCloneSync: SRC_URL is required!" >&2 && exit 1
+	local repoUrl="$2"
+	[ -z "$repoUrl" ] && echo "GitCloneSync: repoUrl is required!" >&2 && return 1
 
-	local BRANCH="$3"
+	local specificBranch="$3"
 	
-	local PWD="`pwd`"
+	local currentPath="`pwd`"
 	
-	if [ -d "$TGT_DIR" ] ; then
-		cd "$TGT_DIR"
-		[ -d ".git" ] || ({
-			[ -z "`git ls-remote "$SRC_URL" || echo fuck`" ] && ({
-				git init
-				git remote add origin "$SRC_URL"
-				git add .
-				git commit -m "Initial commit"
-				git push -u origin master
-			});
-		});
+	if [ -d "$tgtPath" ] ; then
+		cd "$tgtPath"
+		if [ ! -d ".git" ] && [ -z "`git ls-remote --exit-code -h "$repoUrl" || echo failed`" ] ; then
+			git init
+			git remote add origin "$repoUrl"
+			git add .
+			git commit -m "GitCloneSync: Initial commit"
+			git push -u origin master
+		fi
 		
 		git rev-parse --abbrev-ref HEAD > /dev/null \
-				&& [ "`git rev-parse --abbrev-ref HEAD`" != "${BRANCH:-master}" ] \
-				&& cd "$TGT_DIR/.." \
-				&& rm -rf "$TGT_DIR" \
-			|| true
+			&& [ "`git rev-parse --abbrev-ref HEAD`" != "${specificBranch:-master}" ] \
+			&& cd "$tgtPath/.." \
+			&& rm -rf "$tgtPath" \
+		|| true
 	fi
-	if [ ! -d "$TGT_DIR" ] ; then
-	    echo "$TGT_DIR: creating..."
-	    mkdir -p "$TGT_DIR"
-	    git clone "$SRC_URL" "$TGT_DIR"
+	if [ ! -d "$tgtPath" ] ; then
+	    echo "GitCloneSync: $tgtPath: creating..." >&2
+	    mkdir -p "$tgtPath"
+	    git clone "$repoUrl" "$tgtPath"
 	fi
-    if [ "$NOWRITE" != "true" ] && [ ! -f "$TGT_DIR/README.md" -a ! -f "$TGT_DIR/README.MD" ] ; then
-        cd "$TGT_DIR"
+    if [ "$noWrite" != "true" ] && [ ! -f "$tgtPath/README.md" -a ! -f "$tgtPath/README.MD" ] ; then
+        cd "$tgtPath"
         touch README.md
         git add README.md
         git commit -m "add/touch README"
         git push -u
     fi
-	if [ -d "$TGT_DIR" ] ; then
-	    cd "$TGT_DIR"
-	    echo "$TGT_DIR: updating..."
-	    git remote set-url origin "$SRC_URL"
-	    [ -n $BRANCH ] && git checkout $BRANCH
+	if [ -d "$tgtPath" ] ; then
+	    cd "$tgtPath"
+	    echo "GitCloneSync: $tgtPath: updating..." >&2
+	    git remote set-url origin "$repoUrl"
+	    if [ -n $specificBranch ] ; then
+	    	git checkout $specificBranch
+	    fi
 	    git pull
-	    if [ "$NOPUSH" != "true" ] && git diff --quiet "@{push}" HEAD ; then
+	    if [ "$noPush" != "true" ] && git diff --quiet "@{push}" HEAD ; then
 	    	git push
 	    fi
-	    echo "$TGT_DIR: finished."
+	    echo "GitCloneSync: $tgtPath: finished." >&2
 	fi
 	
-	cd "$PWD"
+	cd "$currentPath"
 }
 
 case "$0" in
 	*/myx.common/bin/git/cloneSync) 
 		if [ -z "$1" ] ; then
 			echo "Syntax: myx.common git/cloneSync [--no-write/--no-push] dst_path repo_url [branch]" >&2
-			echo "    If 'branch' argument is not set, 'master' will be used." >&2
-			echo "    '--no-push' makes it equivalent to: 'myx.common git/clonePull'." >&2
+			echo "    If 'branch' argument is not set, 'master' will be used as default." >&2
+			echo "    '--no-push' implies '--no-write' and is equivalent to: 'myx.common git/clonePull'." >&2
 			exit 1
 		fi
 		set -e
