* icons in errors

diff --git a/host/tarball/share/myx.common/bin/git/clonePull b/host/tarball/share/myx.common/bin/git/clonePull
--- a/host/tarball/share/myx.common/bin/git/clonePull
+++ b/host/tarball/share/myx.common/bin/git/clonePull
@@ -6,10 +6,10 @@ GitClonePull(){
 	set -e
 
 	local tgtPath="$1"
-	[ -z "$tgtPath" ] && echo "ERROR: GitClonePull: tgtPath is required!" >&2 && return 1
+	[ -z "$tgtPath" ] && echo "⛔ ERROR: GitClonePull: tgtPath is required!" >&2 && return 1
 
 	local repoUrl="$2"
-	[ -z "$repoUrl" ] && echo "ERROR: GitClonePull: repoUrl is required!" >&2 && return 1
+	[ -z "$repoUrl" ] && echo "⛔ ERROR: GitClonePull: repoUrl is required!" >&2 && return 1
 
 	local specificBranch="$3"
 	
@@ -52,7 +52,7 @@ GitClonePull(){
 		fi
 	fi
 	if [ ! -d "$tgtPath" ] || [ ! -d "$tgtPath/.git" ] ; then
-		echo "ERROR: GitClonePull: error checking out!" >&2 && return 1
+		echo "⛔ ERROR: GitClonePull: error checking out!" >&2 && return 1
 	fi
 
 	echo "GitClonePull: $tgtPath: finished." >&2
diff --git a/host/tarball/share/myx.common/bin/git/cloneSync b/host/tarball/share/myx.common/bin/git/cloneSync
--- a/host/tarball/share/myx.common/bin/git/cloneSync
+++ b/host/tarball/share/myx.common/bin/git/cloneSync
@@ -16,10 +16,10 @@ GitCloneSync(){
 	fi
 
 	local tgtPath="$1"
-	[ -z "$tgtPath" ] && echo "ERROR: GitCloneSync: tgtPath is required!" >&2 && return 1
+	[ -z "$tgtPath" ] && echo "⛔ ERROR: GitCloneSync: tgtPath is required!" >&2 && return 1
 
 	local repoUrl="$2"
-	[ -z "$repoUrl" ] && echo "ERROR: GitCloneSync: repoUrl is required!" >&2 && return 1
+	[ -z "$repoUrl" ] && echo "⛔ ERROR: GitCloneSync: repoUrl is required!" >&2 && return 1
 
 	local specificBranch="$3"
 	
diff --git a/host/tarball/share/myx.common/bin/which b/host/tarball/share/myx.common/bin/which
--- a/host/tarball/share/myx.common/bin/which
+++ b/host/tarball/share/myx.common/bin/which
@@ -5,7 +5,7 @@
 Which(){
 	local MYXROOT="${MYXROOT:-/usr/local/share/myx.common}"
 	local COMMAND="$1"
-	[ -z "$COMMAND" ] && echo "ERROR: Which: COMMAND argument is required!" >&2 && exit 1
+	[ -z "$COMMAND" ] && echo "⛔ ERROR: Which: COMMAND argument is required!" >&2 && exit 1
 	local CHECK="$MYXROOT/bin/$COMMAND"
 	[ -f "$CHECK" ] && echo "$CHECK" && return 0
 	local CHECK="$MYXROOT/include/obsolete/user/bin/$COMMAND"
