* minor: more pronounced script error messages

diff --git a/host/tarball/share/myx.common/bin/git/clonePull b/host/tarball/share/myx.common/bin/git/clonePull
--- a/host/tarball/share/myx.common/bin/git/clonePull
+++ b/host/tarball/share/myx.common/bin/git/clonePull
@@ -6,10 +6,10 @@ GitClonePull(){
 	set -e
 
 	local tgtPath="$1"
-	[ -z "$tgtPath" ] && echo "GitClonePull: tgtPath is required!" >&2 && return 1
+	[ -z "$tgtPath" ] && echo "ERROR: GitClonePull: tgtPath is required!" >&2 && return 1
 
 	local repoUrl="$2"
-	[ -z "$repoUrl" ] && echo "GitClonePull: repoUrl is required!" >&2 && return 1
+	[ -z "$repoUrl" ] && echo "ERROR: GitClonePull: repoUrl is required!" >&2 && return 1
 
 	local specificBranch="$3"
 	
diff --git a/host/tarball/share/myx.common/bin/lib/fetchStdout b/host/tarball/share/myx.common/bin/lib/fetchStdout
--- a/host/tarball/share/myx.common/bin/lib/fetchStdout
+++ b/host/tarball/share/myx.common/bin/lib/fetchStdout
@@ -7,14 +7,14 @@ FetchStdout(){
 	if [ "$1" = "--local-cache" ] ; then
 		shift
 		local LOCAL_CACHE="$1"
-		[ -z "$LOCAL_CACHE" ] && echo "FetchStdout: The CACHE_ROOT is required!" >&2 && exit 1
+		[ -z "$LOCAL_CACHE" ] && echo "ERROR: FetchStdout: The CACHE_ROOT is required!" >&2 && exit 1
 		shift
 	else
 		local LOCAL_CACHE="$ENV_FETCH_LOCAL_CACHE"
 	fi
 	
 	local URL="$1"
-	[ -z "$URL" ] && echo "FetchStdout: The URL is required!" >&2 && exit 1
+	[ -z "$URL" ] && echo "ERROR: FetchStdout: The URL is required!" >&2 && exit 1
 	
 	set -e
 
diff --git a/host/tarball/share/myx.common/bin/lib/prefix b/host/tarball/share/myx.common/bin/lib/prefix
--- a/host/tarball/share/myx.common/bin/lib/prefix
+++ b/host/tarball/share/myx.common/bin/lib/prefix
@@ -18,7 +18,7 @@ Prefix(){
 
 	case "$1" in
 			"")
-				echo "prefix: prefix text argument is required!" >&2 ; exit 1
+				echo "ERROR: prefix: prefix text argument is required!" >&2 ; exit 1
 				;;
 	        -1)
 				local PREFTEXT="`basename $2`"
diff --git a/host/tarball/share/myx.common/bin/lib/replaceText b/host/tarball/share/myx.common/bin/lib/replaceText
--- a/host/tarball/share/myx.common/bin/lib/replaceText
+++ b/host/tarball/share/myx.common/bin/lib/replaceText
@@ -17,8 +17,8 @@ ReplaceText(){
 	esac
 
 	local fileName="$1"
-	[ ! -z "$fileName" ] || { echo "ReplaceText: fileName argument is required!" >&2 ; return 1 ; }
-	[ -f "$fileName" ] || { echo "ReplaceText: $fileName file is expected!" >&2 ; return 1 ; }
+	[ ! -z "$fileName" ] || { echo "ERROR: ReplaceText: fileName argument is required!" >&2 ; return 1 ; }
+	[ -f "$fileName" ] || { echo "ERROR: ReplaceText: $fileName file is expected!" >&2 ; return 1 ; }
 	
 	local textSearch="$( echo "$2" | sed -e "$escapeFn" )" 
 	local textReplace="$( echo "$3" | sed -e "$escapeFn" )"
