* refactor, update method definition formats

diff --git a/host/tarball/share/myx.common/bin/os/getBaseHomeDirectory b/host/tarball/share/myx.common/bin/os/getBaseHomeDirectory
--- a/host/tarball/share/myx.common/bin/os/getBaseHomeDirectory
+++ b/host/tarball/share/myx.common/bin/os/getBaseHomeDirectory
@@ -2,9 +2,9 @@
 
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
-GetBaseHomeDirectory(){
+OsGetBaseHomeDirectory(){
 	# `echo /home`
-	echo "ERROR: GetBaseHomeDirectory must be re-implemented" >&2
+	echo "ERROR: OsGetBaseHomeDirectory must be re-implemented" >&2
 	exit 1
 }
 
@@ -16,6 +16,6 @@ case "$0" in
 			exit 1
 		fi
 		set -e
-		GetBaseHomeDirectory "$@"
+		OsGetBaseHomeDirectory "$@"
 	;;
 esac
diff --git a/host/tarball/share/myx.common/bin/os/getCommonScreenRc b/host/tarball/share/myx.common/bin/os/getCommonScreenRc
--- a/host/tarball/share/myx.common/bin/os/getCommonScreenRc
+++ b/host/tarball/share/myx.common/bin/os/getCommonScreenRc
@@ -2,9 +2,9 @@
 
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
-GetCommonScreenRc(){
+OsGetCommonScreenRc(){
 	# `echo /usr/local/etc/screenrc`
-	echo "ERROR: GetCommonScreenRc must be re-implemented" >&2
+	echo "ERROR: OsGetCommonScreenRc must be re-implemented" >&2
 	exit 1
 }
 
@@ -16,6 +16,6 @@ case "$0" in
 			exit 1
 		fi
 		set -e
-		GetCommonScreenRc "$@"
+		OsGetCommonScreenRc "$@"
 	;;
 esac
diff --git a/host/tarball/share/myx.common/bin/os/getCpuCount b/host/tarball/share/myx.common/bin/os/getCpuCount
--- a/host/tarball/share/myx.common/bin/os/getCpuCount
+++ b/host/tarball/share/myx.common/bin/os/getCpuCount
@@ -2,8 +2,8 @@
 
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
-GetCpuCount(){
-	echo "ERROR: GetCpuCount must be re-implemented" >&2
+OsGetCpuCount(){
+	echo "ERROR: OsGetCpuCount must be re-implemented" >&2
 	exit 1
 }
 
@@ -15,6 +15,6 @@ case "$0" in
 			exit 1
 		fi
 		set -e
-		GetCpuCount "$@"
+		OsGetCpuCount "$@"
 	;;
 esac
diff --git a/host/tarball/share/myx.common/bin/os/getRamBytes b/host/tarball/share/myx.common/bin/os/getRamBytes
--- a/host/tarball/share/myx.common/bin/os/getRamBytes
+++ b/host/tarball/share/myx.common/bin/os/getRamBytes
@@ -2,8 +2,8 @@
 
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
-GetRamBytes(){
-	echo "ERROR: GetRamBytes must be re-implemented" >&2
+OsGetRamBytes(){
+	echo "ERROR: OsGetRamBytes must be re-implemented" >&2
 	exit 1
 }
 
@@ -15,6 +15,6 @@ case "$0" in
 			exit 1
 		fi
 		set -e
-		GetRamBytes "$@"
+		OsGetRamBytes "$@"
 	;;
 esac
diff --git a/host/tarball/share/myx.common/bin/os/getRootHomeDirectory b/host/tarball/share/myx.common/bin/os/getRootHomeDirectory
--- a/host/tarball/share/myx.common/bin/os/getRootHomeDirectory
+++ b/host/tarball/share/myx.common/bin/os/getRootHomeDirectory
@@ -2,9 +2,9 @@
 
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
-GetRootHomeDirectory(){
+OsGetRootHomeDirectory(){
 	# `echo /root`
-	echo "ERROR: GetRootHomeDirectory must be re-implemented" >&2
+	echo "ERROR: OsGetRootHomeDirectory must be re-implemented" >&2
 	exit 1
 }
 
@@ -16,6 +16,6 @@ case "$0" in
 			exit 1
 		fi
 		set -e
-		GetRootHomeDirectory "$@"
+		OsGetRootHomeDirectory "$@"
 	;;
 esac
diff --git a/host/tarball/share/myx.common/bin/os/getWheelGroupNames b/host/tarball/share/myx.common/bin/os/getWheelGroupNames
--- a/host/tarball/share/myx.common/bin/os/getWheelGroupNames
+++ b/host/tarball/share/myx.common/bin/os/getWheelGroupNames
@@ -2,9 +2,9 @@
 
 ##### !!! THIS SCRIPT MUST BE OVERRIDEN IN OS-DEPENDENT IMPLEMENTATION !!! #####
 
-GetWheelGroupNames(){
+OsGetWheelGroupNames(){
 	# `echo wheel`
-	echo "ERROR: GetWheelGroupNames must be re-implemented" >&2
+	echo "ERROR: OsGetWheelGroupNames must be re-implemented" >&2
 	exit 1
 }
 
@@ -17,6 +17,6 @@ case "$0" in
 			exit 1
 		fi
 		set -e
-		GetWheelGroupNames "$@"
+		OsGetWheelGroupNames "$@"
 	;;
 esac
