* cat and setup/machine - cosmetics

diff --git a/host/tarball/share/myx.common/bin/cat b/host/tarball/share/myx.common/bin/cat
--- a/host/tarball/share/myx.common/bin/cat
+++ b/host/tarball/share/myx.common/bin/cat
@@ -4,16 +4,21 @@
 
 Cat(){
 	local MYXROOT="${MYXROOT:-/usr/local/share/myx.common}"
-	local EXECUTE="sed -n '/^case \"\$0\" in/q;p' \"\$CHECK\""
-	if [ "--full" = "$1" ] ; then
-		local EXECUTE='cat "$CHECK"' ; shift
+
+	local EXECUTE="sed '"'/^case "$0" in/,$d'"'"
+	if [ --full = "$1" ]; then
+		EXECUTE=cat ; shift
 	fi
-	local COMMAND="$1"
-	[ -z "$COMMAND" ] && echo "⛔ ERROR: Cat: COMMAND argument is required!" >&2 && exit 1
-	local CHECK="$MYXROOT/bin/$COMMAND"
-	[ -f "$CHECK" ] && eval $EXECUTE && return 0
-	local CHECK="$MYXROOT/include/obsolete/user/bin/$COMMAND"
-	[ -f "$CHECK" ] && eval $EXECUTE && return 0
+
+	local COMMAND="$1" DIR CHECK
+	[ -n "$COMMAND" ] || { echo "⛔ ERROR: Cat: COMMAND argument is required!" >&2; exit 1; }
+	for DIR in bin include/os-$(uname)/bin include/obsolete/user/bin; do
+		CHECK="$MYXROOT/$DIR/$COMMAND" ; echo "$CHECK"
+		if [ -f "$CHECK" ]; then
+			eval $EXECUTE "$CHECK"
+			return 0
+		fi
+	done
 	return 1
 }
 
@@ -21,7 +26,7 @@ case "$0" in
 	*/myx.common/bin/cat) 
 		if [ -z "$1" ] ; then
 			echo "Syntax: myx.common cat [--full] <command>" >&2
-			echo "    outputs a source code to stdout, cutting the standalone execution part (including help messages) or dies with error exit code." >&2
+			echo "    outputs a source code to stdout, cutting the standalone execution part." >&2
 			echo "  NOTE: use --full option to get full source code." >&2
 			exit 1
 		fi
