+ --full option to cat command, defaults to embeddable short version

diff --git a/host/tarball/share/myx.common/bin/cat b/host/tarball/share/myx.common/bin/cat
--- a/host/tarball/share/myx.common/bin/cat
+++ b/host/tarball/share/myx.common/bin/cat
@@ -3,20 +3,25 @@
 # This script is universal for FreeBSD, Darwin, Ubuntu.
 
 Cat(){
+	local EXECUTE="sed -n '/^case \"\$0\" in/q;p' \"\$CHECK\""
+	if [ "--full" = "$1" ] ; then
+		local EXECUTE='cat "$CHECK"' ; shift
+	fi
 	local COMMAND="$1"
 	[ -z "$COMMAND" ] && echo "ERROR: Cat: COMMAND argument is required!" >&2 && exit 1
 	local CHECK="/usr/local/share/myx.common/bin/$COMMAND"
-	[ -f "$CHECK" ] && cat "$CHECK" && return 0
+	[ -f "$CHECK" ] && eval $EXECUTE && return 0
 	local CHECK="/usr/local/share/myx.common/include/obsolete/user/bin/$COMMAND"
-	[ -f "$CHECK" ] && cat "$CHECK" && return 0
+	[ -f "$CHECK" ] && eval $EXECUTE && return 0
 	return 1
 }
 
 case "$0" in
 	*/myx.common/bin/cat) 
 		if [ -z "$1" ] ; then
-			echo "Syntax: myx.common cat MYX-COMMON-COMMAND" >&2
-			echo "    outputs a source code to stdout or dies with error exit code." >&2
+			echo "Syntax: myx.common cat [--full] <command>" >&2
+			echo "    outputs a source code to stdout, cutting the standalone execution part (including help messages) or dies with error exit code." >&2
+			echo "  NOTE: use --full option to get full source code." >&2
 			exit 1
 		fi
 		set -e
